#!/bin/bash

textfile=$(cat /var/lib/dhcp/dhcpd.leases)
cp /var/lib/dhcp/dhcpd.leases /var/lib/dhcp/dhcp.leases2
ex -s -c '1d|x' /var/lib/dhcp/dhcp.leases2
ex -s -c '1d|x' /var/lib/dhcp/dhcp.leases2
ex -s -c '1d|x' /var/lib/dhcp/dhcp.leases2
ex -s -c '1d|x' /var/lib/dhcp/dhcp.leases2
ex -s -c '1d|x' /var/lib/dhcp/dhcp.leases2
ex -s -c '1d|x' /var/lib/dhcp/dhcp.leases2
sed -i '/uid/d' /var/lib/dhcp/dhcp.leases2
echo "" > /var/www/html/mysql/unknown.txt
mac="sometext"
while [ $mac != "" ]
do
    object=$(sed -n '/lease/,/}/p; /}/q' /var/lib/dhcp/dhcp.leases2)
    mac=$(echo "$object" | grep -oEa "([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}")
    counter=$(mysql --user=asd --password=asd --database=asd -N -e "SELECT komputery.id FROM komputery WHERE id=(SELECT max(id) FROM komputery)")
    maceq=$(mysql --user=asd --password=asd --database=asd -N -e "SELECT LOWER(komputery.mac) FROM komputery")
    check=$(echo "$maceq" | grep "$mac")
    checklen=${#check}
#    echo "$checklen"
    if [ $checklen -ne 17 ]
    then
	ip=$(echo "$object" | grep -oEa "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
	vendor=$(echo "$object" | sed -n -e 's/^.*= //p')
	hname=$(echo "$object" | sed -n -e 's/^.*client-hostname //p')
	datat=$(echo "$object" | sed -n -e 's/^.*starts //p')
	echo "_________________________________________________________________________" >> /var/www/html/mysql/unknown.txt
	echo "$ip" >> /var/www/html/mysql/unknown.txt
	echo "$vendor" >> /var/www/html/mysql/unknown.txt
	echo "$mac" >> /var/www/html/mysql/unknown.txt
	echo "$hname" >> /var/www/html/mysql/unknown.txt
	echo "" >> /var/www/html/mysql/unknown.txt
	echo "$datat" >> /var/www/html/mysql/unknown.txt
#	echo "$ip"
#    else
#	ip=$(echo "$object" | grep -oEa "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
#	echo "ten jest w bazie"
#	echo "$ip"
    fi
    lines=$(echo "$object" | wc -l)
    while [ $lines -gt 0 ]
    do
	ex -s -c '1d|x' /var/lib/dhcp/dhcp.leases2
	lines=$((lines-1))
    done
done
rm /var/lib/dhcp/dhcp.leases2
